### ISSUE TITLE
HTTP checks failing on binary responses

### ISSUE THREAD

**Issue by mdesouky** [base2Services/aws-lambda-http-check#3]
the function apparently fails when the response is a binary object not plain text
From Cloudwatch logs:

Failed to connect to https://akorg205.tunedglobal.com/testassets/tuned.jpg
'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by Guslington** [comment]
added support for images https://github.com/base2Services/aws-lambda-http-check/tree/master#images by comparing against md5 hash of the image
