### ISSUE TITLE
Stack 'aws-python3-dev' does not exist

### ISSUE THREAD

**Issue by davevdm1968** [base2Services/aws-lambda-http-check#9]
I'm getting the following error

Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
...
Serverless: Stack create finished...
 
  Serverless Error ---------------------------------------
 
  Stack 'aws-python3-dev' does not exist
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.18.1
     Framework Version:         2.10.0 (standalone)
     Plugin Version:            4.1.1
     SDK Version:               2.3.2
     Components Version:        3.3.0

**Comment by Guslington** [comment]
Hi @davevdm1968 

The serverless template could be out of date, however the preferred deployment method is aws sam-cli using the template.yaml. apologies the doco is yet to be updated for using aws sam.

**Comment by Guslington** [comment]
updated docs to reflect deployment changes https://github.com/base2Services/aws-lambda-http-check/commit/f5b1a02ae6246d587de989925af1002858f46297
